#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: configure
#
Name     : libe-book
Version  : 0.1.3
Release  : 11
URL      : https://dev-www.libreoffice.org/src/libe-book-0.1.3.tar.xz
Source0  : https://dev-www.libreoffice.org/src/libe-book-0.1.3.tar.xz
Summary  : Library for parsing various reflowable ebook formats
Group    : Development/Tools
License  : MPL-2.0-no-copyleft-exception
Requires: libe-book-bin = %{version}-%{release}
Requires: libe-book-lib = %{version}-%{release}
Requires: libe-book-license = %{version}-%{release}
BuildRequires : boost-dev
BuildRequires : buildreq-configure
BuildRequires : doxygen
BuildRequires : gperf
BuildRequires : pkgconfig(cppunit)
BuildRequires : pkgconfig(icu-i18n)
BuildRequires : pkgconfig(liblangtag)
BuildRequires : pkgconfig(librevenge-0.0)
BuildRequires : pkgconfig(librevenge-generators-0.0)
BuildRequires : pkgconfig(librevenge-stream-0.0)
BuildRequires : pkgconfig(libxml-2.0)
BuildRequires : pkgconfig(zlib)
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}
Patch1: backport-bool.patch

%description
libe-book is a library and a set of tools for reading and converting
various reflowable e-book formats.

%package bin
Summary: bin components for the libe-book package.
Group: Binaries
Requires: libe-book-license = %{version}-%{release}

%description bin
bin components for the libe-book package.


%package dev
Summary: dev components for the libe-book package.
Group: Development
Requires: libe-book-lib = %{version}-%{release}
Requires: libe-book-bin = %{version}-%{release}
Provides: libe-book-devel = %{version}-%{release}
Requires: libe-book = %{version}-%{release}

%description dev
dev components for the libe-book package.


%package doc
Summary: doc components for the libe-book package.
Group: Documentation

%description doc
doc components for the libe-book package.


%package lib
Summary: lib components for the libe-book package.
Group: Libraries
Requires: libe-book-license = %{version}-%{release}

%description lib
lib components for the libe-book package.


%package license
Summary: license components for the libe-book package.
Group: Default

%description license
license components for the libe-book package.


%prep
%setup -q -n libe-book-0.1.3
cd %{_builddir}/libe-book-0.1.3
%patch1 -p1
pushd ..
cp -a libe-book-0.1.3 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1685637222
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export FCFLAGS="$FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export FFLAGS="$FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export CXXFLAGS="$CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
%configure --disable-static
make  %{?_smp_mflags}

unset PKG_CONFIG_PATH
pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3"
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3"
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3"
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3"
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3"
%configure --disable-static
make  %{?_smp_mflags}
popd
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make %{?_smp_mflags} check
cd ../buildavx2;
make %{?_smp_mflags} check || :

%install
export SOURCE_DATE_EPOCH=1685637222
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/libe-book
cp %{_builddir}/libe-book-%{version}/COPYING %{buildroot}/usr/share/package-licenses/libe-book/9744cedce099f727b327cd9913a1fdc58a7f5599 || :
pushd ../buildavx2/
%make_install_v3
popd
%make_install
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/V3/usr/bin/ebook2html
/V3/usr/bin/ebook2raw
/V3/usr/bin/ebook2text
/usr/bin/ebook2html
/usr/bin/ebook2raw
/usr/bin/ebook2text

%files dev
%defattr(-,root,root,-)
/usr/include/libe-book-0.1/libe-book/EBOOKDocument.h
/usr/include/libe-book-0.1/libe-book/libe-book.h
/usr/lib64/libe-book-0.1.so
/usr/lib64/pkgconfig/libe-book-0.1.pc

%files doc
%defattr(0644,root,root,0755)
/usr/share/doc/libe\-book/*

%files lib
%defattr(-,root,root,-)
/V3/usr/lib64/libe-book-0.1.so.1.0.3
/usr/lib64/libe-book-0.1.so.1
/usr/lib64/libe-book-0.1.so.1.0.3

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/libe-book/9744cedce099f727b327cd9913a1fdc58a7f5599
